% downlaod and save TLEs from celestrak
% WARNING: downloads text files from internet
%% siddharth@deore.in

clc; clear;
prefix='http://www.celestrak.com/NORAD/elements/';
websave('TLE\visual.txt',strcat(prefix,'visual.txt'))

%% update EOP data, space weather data

websave('SpaceData\EOP-Last5Years.txt','http://celestrak.com/SpaceData/EOP-Last5Years.txt')
websave('SpaceData\SW-Last5Years.txt','http://celestrak.com/SpaceData/SW-Last5Years.txt')
websave('SpaceData\eop20130101.txt','http://celestrak.com/SpaceData/eop20130101.txt')

%%{
prefix='http://www.celestrak.com/NORAD/elements/';
websave('TLE\tle-new.txt',strcat(prefix,'tle-new.txt'));
websave('TLE\stations.txt',strcat(prefix,'stations.txt'));
websave('TLE\visual.txt',strcat(prefix,'visual.txt'));
websave('TLE\active.txt',strcat(prefix,'active.txt'));
websave('TLE\analyst.txt',strcat(prefix,'analyst.txt'));
websave('TLE\2019-006.txt',strcat(prefix,'2019-006.txt'));
websave('TLE\1999-025.txt',strcat(prefix,'1999-025.txt'));
websave('TLE\iridium-33-debris.txt',strcat(prefix,'iridium-33-debris.txt'));
websave('TLE\cosmos-2251-debris.txt',strcat(prefix,'cosmos-2251-debris.txt'));
websave('TLE\2012-044.txt',strcat(prefix,'2012-044.txt'));
websave('TLE\weather.txt',strcat(prefix,'weather.txt'));
websave('TLE\noaa.txt',strcat(prefix,'noaa.txt'));
websave('TLE\goes.txt',strcat(prefix,'goes.txt'));
websave('TLE\resource.txt',strcat(prefix,'resource.txt'));
websave('TLE\sarsat.txt',strcat(prefix,'sarsat.txt'));
websave('TLE\dmc.txt',strcat(prefix,'dmc.txt'));
websave('TLE\tdrss.txt',strcat(prefix,'tdrss.txt'));
websave('TLE\argos.txt',strcat(prefix,'argos.txt'));
websave('TLE\planet.txt',strcat(prefix,'planet.txt'));
websave('TLE\spire.txt',strcat(prefix,'spire.txt'));
websave('TLE\geo.txt',strcat(prefix,'geo.txt'));
websave('TLE\intelsat.txt',strcat(prefix,'intelsat.txt'));
websave('TLE\ses.txt',strcat(prefix,'ses.txt'));
websave('TLE\iridium.txt',strcat(prefix,'iridium.txt'));
websave('TLE\iridium-NEXT.txt',strcat(prefix,'iridium-NEXT.txt'));
websave('TLE\orbcomm.txt',strcat(prefix,'orbcomm.txt'));
websave('TLE\globalstar.txt',strcat(prefix,'globalstar.txt'));
websave('TLE\amateur.txt',strcat(prefix,'amateur.txt'));
websave('TLE\x-comm.txt',strcat(prefix,'x-comm.txt'));
websave('TLE\other-comm.txt',strcat(prefix,'other-comm.txt'));
websave('TLE\satnogs.txt',strcat(prefix,'satnogs.txt'));
websave('TLE\gorizont.txt',strcat(prefix,'gorizont.txt'));
websave('TLE\raduga.txt',strcat(prefix,'raduga.txt'));
websave('TLE\molniya.txt',strcat(prefix,'molniya.txt'));
websave('TLE\gps-ops.txt',strcat(prefix,'gps-ops.txt'));
websave('TLE\glo-ops.txt',strcat(prefix,'glo-ops.txt'));
websave('TLE\galileo.txt',strcat(prefix,'galileo.txt'));
websave('TLE\beidou.txt',strcat(prefix,'beidou.txt'));
websave('TLE\sbas.txt',strcat(prefix,'sbas.txt'));
websave('TLE\nnss.txt',strcat(prefix,'nnss.txt'));
websave('TLE\musson.txt',strcat(prefix,'musson.txt'));
websave('TLE\science.txt',strcat(prefix,'science.txt'));
websave('TLE\geodetic.txt',strcat(prefix,'geodetic.txt'));
websave('TLE\engineering.txt',strcat(prefix,'engineering.txt'));
websave('TLE\education.txt',strcat(prefix,'education.txt'));
websave('TLE\military.txt',strcat(prefix,'military.txt'));
websave('TLE\radar.txt',strcat(prefix,'radar.txt'));
websave('TLE\cubesat.txt',strcat(prefix,'cubesat.txt'));
websave('TLE\other.txt',strcat(prefix,'other.txt'));
%%}

%{
urlwrite(strcat(prefix,'tle-new.txt'),'TLE\tle-new.txt');
urlwrite(strcat(prefix,'stations.txt'),'TLE\stations.txt');
urlwrite(strcat(prefix,'visual.txt'),'TLE\visual.txt');
urlwrite(strcat(prefix,'active.txt'),'TLE\active.txt');
urlwrite(strcat(prefix,'analyst.txt'),'TLE\analyst.txt');
urlwrite(strcat(prefix,'2019-006.txt'),'TLE\2019-006.txt');
urlwrite(strcat(prefix,'1999-025.txt'),'TLE\1999-025.txt');
urlwrite(strcat(prefix,'iridium-33-debris.txt'),'TLE\iridium-33-debris.txt');
urlwrite(strcat(prefix,'cosmos-2251-debris.txt'),'TLE\cosmos-2251-debris.txt');
urlwrite(strcat(prefix,'2012-044.txt'),'TLE\2012-044.txt');
urlwrite(strcat(prefix,'weather.txt'),'TLE\weather.txt');
urlwrite(strcat(prefix,'noaa.txt'),'TLE\noaa.txt');
urlwrite(strcat(prefix,'goes.txt'),'TLE\goes.txt');
urlwrite(strcat(prefix,'resource.txt'),'TLE\resource.txt');
urlwrite(strcat(prefix,'sarsat.txt'),'TLE\sarsat.txt');
urlwrite(strcat(prefix,'dmc.txt'),'TLE\dmc.txt');
urlwrite(strcat(prefix,'tdrss.txt'),'TLE\tdrss.txt');
urlwrite(strcat(prefix,'argos.txt'),'TLE\argos.txt');
urlwrite(strcat(prefix,'planet.txt'),'TLE\planet.txt');
urlwrite(strcat(prefix,'spire.txt'),'TLE\spire.txt');
urlwrite(strcat(prefix,'geo.txt'),'TLE\geo.txt');
urlwrite(strcat(prefix,'intelsat.txt'),'TLE\intelsat.txt');
urlwrite(strcat(prefix,'ses.txt'),'TLE\ses.txt');
urlwrite(strcat(prefix,'iridium.txt'),'TLE\iridium.txt');
urlwrite(strcat(prefix,'iridium-NEXT.txt'),'TLE\iridium-NEXT.txt');
urlwrite(strcat(prefix,'orbcomm.txt'),'TLE\orbcomm.txt');
urlwrite(strcat(prefix,'globalstar.txt'),'TLE\globalstar.txt');
urlwrite(strcat(prefix,'amateur.txt'),'TLE\amateur.txt');
urlwrite(strcat(prefix,'x-comm.txt'),'TLE\x-comm.txt');
urlwrite(strcat(prefix,'other-comm.txt'),'TLE\other-comm.txt');
urlwrite(strcat(prefix,'satnogs.txt'),'TLE\satnogs.txt');
urlwrite(strcat(prefix,'gorizont.txt'),'TLE\gorizont.txt');
urlwrite(strcat(prefix,'raduga.txt'),'TLE\raduga.txt');
urlwrite(strcat(prefix,'molniya.txt'),'TLE\molniya.txt');
urlwrite(strcat(prefix,'gps-ops.txt'),'TLE\gps-ops.txt');
urlwrite(strcat(prefix,'glo-ops.txt'),'TLE\glo-ops.txt');
urlwrite(strcat(prefix,'galileo.txt'),'TLE\galileo.txt');
urlwrite(strcat(prefix,'beidou.txt'),'TLE\beidou.txt');
urlwrite(strcat(prefix,'sbas.txt'),'TLE\sbas.txt');
urlwrite(strcat(prefix,'nnss.txt'),'TLE\nnss.txt');
urlwrite(strcat(prefix,'musson.txt'),'TLE\musson.txt');
urlwrite(strcat(prefix,'science.txt'),'TLE\science.txt');
urlwrite(strcat(prefix,'geodetic.txt'),'TLE\geodetic.txt');
urlwrite(strcat(prefix,'engineering.txt'),'TLE\engineering.txt');
urlwrite(strcat(prefix,'education.txt'),'TLE\education.txt');
urlwrite(strcat(prefix,'military.txt'),'TLE\military.txt');
urlwrite(strcat(prefix,'radar.txt'),'TLE\radar.txt');
urlwrite(strcat(prefix,'cubesat.txt'),'TLE\cubesat.txt');
urlwrite(strcat(prefix,'other.txt'),'TLE\other.txt');
%}